import { GetStaticProps, InferGetStaticPropsType, type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/Navbar";

const Home: NextPage = ({
  posts,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const { data: session } = useSession();
  console.log("session data", session);
  console.log("all post", posts);
  return (
    <>
      <Head>
        <title>Susutain Hacks</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="text-center">
        {/* Heading */}
        {!session ? (
          <div>
            <h1 className="mt-4 text-5xl font-bold text-gray-800">
              Welcome to Sustain Hacks,
            </h1>
          </div>
        ) : (
          <div>
            <h1 className="mt-4 text-5xl font-bold text-gray-800">
              Welcome to Sustain Hacks, {session?.user?.name}
            </h1>
          </div>
        )}

        {/* Active / Inactive bar */}
        <div className="mt-10 flex justify-center">
          <div className="flex gap-2 rounded-2xl border-2  px-2">
            <div className="rounded-2xl border-2 border-green-600 px-2 py-1">
              active bar
            </div>
            <div className="rounded-2xl border-2 border-rose-900 px-2 py-1">
              Inactive bar
            </div>
          </div>
        </div>
        {/* Posts */}
        <div className="mt-10 grid grid-cols-4 gap-4">
          {posts?.data.length > 0 &&
            posts?.data?.map((post: any) => (
              <div>
                <div className="col-span-1 rounded-lg bg-white shadow-lg">
                  <div>{post.title}</div>
                  <div> {post.content}</div>
                  <div>
                    {" "}
                    <Image
                      width={100}
                      height={100}
                      src={post.file}
                      alt={post.title}
                    ></Image>{" "}
                  </div>
                </div>
              </div>
            ))}
        </div>

        {/* Create Post */}
        <div className="mt-20 flex justify-center">
          <button className="hover: w-40 rounded-2xl border-2 bg-green-600 px-2 py-2 text-white hover:border-slate-800 hover:bg-white hover:text-slate-800">
            <Link href={"/create-post"}>Create Post</Link>
          </button>
        </div>
      </main>
    </>
  );
};
export const getStaticProps: GetStaticProps = async (context) => {
  let res = await fetch("http://localhost:3000/api/posts", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
  let posts: [] = await res.json();

  return {
    props: { posts },
  };
};
export default Home;
