import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";

const Home = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Resuse</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className="text-center">
        <div>
          <div className="mt-40 px-20">
            {/* Heading */}
            {!session ? (
              <div>
                <h1 className="mt-4 px-20 text-7xl font-bold text-gray-800">
                  Welcome to Donate,
                </h1>
              </div>
            ) : (
              <div>
                <h1 className="mt-4   text-7xl font-bold text-gray-800">
                  Welcome to Donate,
                  <br />
                  {session?.user?.name}
                </h1>
              </div>
            )}
          </div>
          <div className="mt-10 flex justify-center">
            <p className="px-96 text-xl font-extralight text-gray-500">
              About Project Lorem ipsum dolor sit amet consectetur adipisicing
              elit. Quisquam, quod. Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Quisquam, quod. Lorem ipsum dolor sit amet
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
